[tokamak]
name = "FT2"
R0 = 0.80          # [m] Major radius
a  = 0.6           # [m] Minor radius
# параметры выше уже используються
#b = 3.3           # [m] Vertical minor radius (for elongation)
#wall_material = "Be"

[initial_conditions]
ppar = -0.1
pperp = 0.025
r = 0.2
thet = 0
fi = 0


# тут можно придумывать все что угодно
[discharge.main]
shot_number = 12345
B0 = 5.3           # [T] Toroidal field on axis
Ip = 15.0          # [MA] Plasma current
Uloop = 0.1        # [V] Loop voltage

[discharge.perturbations]
n = 0              # Toroidal mode number
delfi = 0.0       # Relative amplitude
nfi = 0           # Number of field periods
delr = 0.0        # Radial perturbation factor

# Начальные условия для солвера (профили)
[discharge.profiles]
sf0 = 1.0          # Safety factor on axis
sfb = 3.5          # Safety factor at boundary